# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/registrationVK?id=99
Accept: application/json

###

POST http://localhost:8080/registrationVK?first_name=m&last_name=m&herf=user&mid=123



###

POST http://localhost:8080/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###

POST http://localhost:8080/newCust
Content-Type: application/x-www-form-urlencoded

###

POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=ok&password=ok

###

POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=dgergaergae&password=ok

###

POST http://localhost:8080/registration
Content-Type: application/x-www-form-urlencoded

firstName=firstName&lastName=last_name&mobile=mobile&email=email&username=username&password=pass

###

POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=username&password=pass

###

POST http://localhost:8080/changeSet
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element
firstName=Name&lastName=name&mobile=000&email=mail

###

GET http://localhost:8080/get
Accept: application/json

###